<?php
/**
 * This file is automatically generated from Chatwing API
 * @author chatwing
 */
if ( ! defined( 'ABSPATH' ) ) exit;
return array(
    'user/chatbox/list' => array(
        'type' => 'get',
        'auth' => true
    ),
    'chatbox/read' => array(
        'type' => 'get',
        'auth' => true
    ),
    'app/plugin/authenticate' => array(
        'type' => 'post',
        'auth' => true
    ),
    'app/plugin/get_access_token' => array(
        'type' => 'get',
        'auth' => false
    )
);